### ISSUE TITLE
Setup Kanban Board

### ISSUE THREAD

**Issue by cherelemma** [Microverse-Fullstack-Program/rails-recipe-app-v2#16]
We are 3 in this team @cherelemma #1, @Enning94 #2 and  @Odongo006#3:

- Here is a link to the [Kanban board](https://github.com/Microverse-Fullstack-Program/rails-recipe-app-v2/projects/1)
- Here is a link to the [repo](https://github.com/Microverse-Fullstack-Program/rails-recipe-app-v2)

**Comment by Ibizugbe** [comment]
Hi @Team👋🏼👋🏼👋🏼, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights✅✅✅

- [x] All tasks are captured in the cards and points are fairly distributed👍🏼.
- [x] Project contains the required columns👍🏼.
- [x] Link to project has been added to the issue👍🏼.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
